# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test
on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Runs this workflow
      env:
        SEARCH_GITHUB_TOKEN: ${{ secrets.SEARCH_GITHUB_TOKEN }}
      uses:  jake82w/code-organizer-merge-on-green@master
